# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        Cookway\Domain\Core\User:
            algorithm: bcrypt
            cost: 12
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        user:
            id: 'app.core.security.user_provider'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/security/login
            anonymous: ~
        api_doc:
            pattern: ^/api/doc$
            anonymous: true
        api:
            pattern: ^/api
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
            stateless: true
