imports:
    - { resource: services/recipe.yml }
    - { resource: services/dictionary.yml }
    - { resource: services/core.yml }
services:
    AppBundle\DataFixtures\:
        resource: '../../src/AppBundle/DataFixtures'
        tags: ['doctrine.fixture.orm']
