services:
    app.recipe.ingredients_repository:
        class: Cookway\Infrastructure\Recipe\DoctrineIngredientsRepository
        arguments:
            - '@doctrine.orm.entity_manager'
    app.recipe.recipes_repository:
        class: Cookway\Infrastructure\Recipe\DoctrineRecipesRepository
        arguments:
            - '@doctrine.orm.entity_manager'
    app.recipe.photos_repository:
        class: Cookway\Infrastructure\Recipe\DoctrinePhotosRepository
        arguments:
            - '@doctrine.orm.entity_manager'
    app.recipe.new_recipe_handler:
        class: Cookway\Application\Recipe\NewRecipeHandler
        arguments: {}