services:
    AppBundle\DataFixtures\:
        resource: '../../src/AppBundle/DataFixtures'
        tags: ['doctrine.fixture.orm']
    app.base_controller:
        class: AppBundle\Controller\BaseController
        arguments:
            - '@tactician.commandbus'
    app.recipe.ingredients_repository:
        class: Cookway\Infrastructure\Recipe\DoctrineIngredientsRepository
        arguments:
            - '@doctrine.orm.entity_manager'
    app.recipe.unit_repository:
        class: Cookway\Infrastructure\Recipe\DoctrineUnitsRepository
        arguments:
            - '@doctrine.orm.entity_manager'
    app.recipe.recipes_repository:
        class: Cookway\Infrastructure\Recipe\DoctrineRecipesRepository
        arguments:
            - '@doctrine.orm.default_entity_manager'
    app.recipe.photos_repository:
        class: Cookway\Infrastructure\Recipe\DoctrinePhotosRepository
        arguments:
            - '@doctrine.orm.entity_manager'
    app.recipe.create_recipe_handler:
        class: Cookway\Application\Recipe\CreateRecipeHandler
        arguments:
            - '@app.recipe.recipes_repository'
            - ''
    app.core.users_repository:
        class: Cookway\Infrastructure\Core\DoctrineUserRepository
        arguments:
            - '@doctrine.orm.entity_manager'
    app.core.security.user_provider:
        class: Cookway\Application\Security\UserProvider
        arguments:
            - '@app.core.users_repository'
    app.core.security.login_handler:
        class: Cookway\Application\Security\Command\LoginHandler
        arguments:
            - '@app.core.security.user_provider'
            - '@security.password_encoder'
    app.dictionary.units_ditionary_query:
        class: Cookway\Infrastructure\Dictionary\UnitDictionaryQuery
        arguments:
            - '@app.recipe.unit_repository'