Cookway\Domain\Core\User:
    type: entity
    table: user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            nullable: false
        password:
            type: string
            nullable: false
        salt:
            type: string
            nullable: true
    oneToMany:
        recipes:
            targetEntity: Cookway\Domain\Recipe\Recipe
            mappedBy: author
    manyToMany:
        roles:
            targetEntity: Role
            cascade: ['persist']
            joinTable:
                name: user_role
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    role_id:
                        referencedColumnName: id