Cookway\Domain\Core\Role:
    type: entity
    table: role
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        role:
            type: string
            nullable: false