Cookway\Domain\Recipe\Unit:
    type: entity
    table: unit
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            nullable: false